In [1]:
import numpy as np
import pandas as pd
# GDSC.shape 874 x 7964
GDSC_PDX_Paclitaxel = pd.read_csv('data/GDSC_PDX_Paclitaxel.csv')
GDSC_PDX_Paclitaxel.columns.values[0] = "CELL_LINE_NAME"
GDSC_PDX_Paclitaxel

,CELL_LINE_NAME,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MRPL46,HPR,MIA,LINC00514,OR1D5,ZNF234,MYH4,LINC00526,KRT18P55,TBC1D3P5
0,MC-CAR,-1.184016,0.468235,0.485299,0.951035,0.705346,3.574280,-0.334766,-0.167187,-0.829344,...,0.639887,0.113480,0.157138,-0.504232,0.283905,-0.785013,0.443411,0.684380,-0.006255,1.037289
1,SK-ES-1,0.949128,-0.099122,-1.142175,0.221316,0.582377,-0.500133,0.163121,-1.660569,-0.434605,...,-0.518210,-1.023453,-0.407149,-0.924217,-0.198564,-0.366830,-0.151292,0.246662,-0.534830,-0.214098
2,8-MG-BA,0.788220,0.840168,0.628150,-1.331285,-0.248648,-0.386293,-0.297668,0.815664,-0.212430,...,-1.083025,0.357081,-0.078537,-0.376219,-0.914794,0.283323,-0.551244,-0.333331,0.038996,-0.114577
3,GB-1,0.053174,-0.648190,-0.181854,-0.633104,-0.947646,-0.469195,-0.684658,0.421926,-0.905626,...,-0.830098,-1.200791,-0.194579,-0.275438,-0.562004,0.634896,-0.366795,0.442662,-1.225924,0.757517
4,NCI-H1648,1.519261,-0.368292,0.226856,-0.179698,-0.865956,-0.440831,1.035865,0.896539,1.694665,...,0.313644,-0.783564,-0.480206,-0.311198,-0.414697,-0.112886,-0.841901,0.379371,1.731215,-1.545600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,CL-11,0.509973,0.547057,-0.601671,-0.464114,0.005193,-0.483587,-0.443398,0.765826,-0.753786,...,1.578933,0.599214,0.454603,0.216259,-1.002894,-1.029649,0.684973,-0.045526,-0.431420,-0.068895
395,COR-L95,-0.206808,-1.340759,-0.545395,-0.429504,-0.561951,-0.619859,-0.649944,0.262877,2.319067,...,-2.464711,-0.524581,-0.416340,-0.736149,-1.753831,-0.127193,-0.499025,0.121546,0.148885,-0.132204
396,NCI-H2135,1.066798,0.060061,-0.570217,-0.570037,-0.342490,-0.252140,-0.148907,1.091669,2.366973,...,1.378062,-1.094202,-0.095038,-0.397918,0.051392,-0.628697,0.355916,0.640426,-0.067006,1.074772
397,ME-1,-1.079919,-0.198108,0.063834,0.553150,-0.359821,-0.325923,-0.550151,0.341530,0.670671,...,-0.532261,0.974459,0.303012,-0.517000,-0.301867,1.009828,-0.353051,-1.128451,0.978038,1.259332
398,ROS-50,-1.067755,-0.034873,0.821478,-0.580824,0.084179,0.963640,-0.576919,-1.231046,-0.143699,...,-0.014946,0.146259,-0.283344,-0.069726,1.472417,-0.258656,-0.001025,-0.644533,0.642495,1.238364

In [2]:
GDSC_PDX_Paclitaxel_info = pd.read_csv('data/GDSC_PDX_Paclitaxel_info.csv', index_col=0)
GDSC_PDX_Paclitaxel_info

       CELL_LINE_NAME  MAX_CONC_MICROMOLAR      IC50
1              MC-CAR               0.1024  0.026059
2                 ES3               0.1024  0.823045
3                 ES5               0.1024  1.132950
4                 ES7               0.1024  1.119814
5               EW-11               0.1024  2.753277
..                ...                  ...       ...
422            Toledo               0.1024  0.072571
423           WIL2-NS               0.1024  0.005161
424         WSU-DLCL2               0.1024  0.079155
425  MKL-1-subclone-2               0.1024  0.012390
426             MKL-2               0.1024  0.013689

[426 rows x 3 columns]

In [33]:
# Docetaxel_info.shape 882 x 5
CCLE_PDX_Paclitaxel = pd.read_csv('data/CCLE_PDX_Paclitaxel.csv')
CCLE_PDX_Paclitaxel.columns.values[0] = "CELL_LINE_NAME"
CCLE_PDX_Paclitaxel

,CELL_LINE_NAME,A1BG,A1CF,A2M,A2ML1,A4GALT,A4GNT,AAAS,AACS,AACSP1,...,WWC2,WWC3,WWOX,WWP1,WWP2,WWTR1,XAB2,XAF1,XAGE3,XAGE5
0,22RV1_PROSTATE,0.775266,1.340437,1.125580,0.175305,0.472983,-0.910305,1.741850,1.408660,1.229710,...,1.196219,1.061770,0.964826,1.417611,1.420964,1.132964,1.624045,0.036481,0.358927,0.387453
1,42MGBA_CENTRAL_NERVOUS_SYSTEM,1.133386,-1.026812,0.125871,-1.026812,0.696926,0.228324,1.552878,1.081658,0.444638,...,1.415945,1.177418,0.841848,1.282522,1.232678,1.358025,1.522461,0.804841,-1.026812,-1.026812
2,5637_URINARY_TRACT,0.022117,-0.991209,0.217480,1.012588,1.297478,-0.991209,1.556874,1.199188,-0.991209,...,1.406805,1.408769,0.989993,1.410864,1.295599,1.239702,1.607104,1.030290,-0.991209,-0.991209
3,639V_URINARY_TRACT,0.973198,-1.087801,-0.148105,-0.417490,0.625598,0.241110,1.513675,1.077493,0.091492,...,1.324314,1.219461,-0.164323,1.368473,1.115155,1.246357,1.499558,0.580831,-1.087801,-1.087801
4,697_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,1.169179,-1.028292,0.465891,-0.163033,0.008992,-0.076229,1.611807,0.730032,0.931754,...,0.223194,1.424845,1.191023,1.335067,1.288845,0.891905,1.559839,1.037151,-1.028292,-1.028292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,SKCO1_LARGE_INTESTINE,0.082939,0.069513,0.180665,0.874991,0.360915,0.365550,1.714129,1.308940,-0.054334,...,0.528041,0.257052,0.928405,1.558230,1.466095,1.266036,1.572237,0.133136,-0.889931,-0.889931
465,SNU449_LIVER,0.329194,-0.862985,0.321539,-0.862985,1.240156,0.700469,1.684887,1.295932,0.625017,...,1.438325,1.427298,1.202976,1.637519,1.401277,1.828233,1.593913,0.226257,-0.862985,-0.862985
466,T47D_BREAST,1.370118,0.108176,0.430079,0.639420,1.445329,0.778823,1.922907,1.501275,0.384548,...,1.610535,2.029795,1.379566,1.706726,1.657003,1.570593,1.819676,0.354965,-0.702386,-0.702386
467,UACC257_SKIN,1.022618,-1.018997,1.316034,-0.309005,-1.018997,0.107777,1.599685,0.961408,0.334584,...,1.161265,1.156945,1.152997,1.315930,1.253381,1.402175,1.496510,-0.005438,-1.018997,-1.018997
468,VMRCRCW_KIDNEY,0.648441,1.313671,0.453051,-0.827025,1.388188,0.651751,1.585672,1.174585,0.200293,...,1.576601,1.672691,1.224632,1.514797,1.361650,1.822998,1.588818,1.326480,-0.827025,-0.827025

#### Playground

In [34]:
test = pd.merge(GDSC_PDX_Paclitaxel,
                GDSC_PDX_Paclitaxel_info,
                how='inner',
                on=['CELL_LINE_NAME'])
test

,CELL_LINE_NAME,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MIA,LINC00514,OR1D5,ZNF234,MYH4,LINC00526,KRT18P55,TBC1D3P5,MAX_CONC_MICROMOLAR,IC50
0,MC-CAR,-1.184016,0.468235,0.485299,0.951035,0.705346,3.574280,-0.334766,-0.167187,-0.829344,...,0.157138,-0.504232,0.283905,-0.785013,0.443411,0.684380,-0.006255,1.037289,0.1024,0.026059
1,SK-ES-1,0.949128,-0.099122,-1.142175,0.221316,0.582377,-0.500133,0.163121,-1.660569,-0.434605,...,-0.407149,-0.924217,-0.198564,-0.366830,-0.151292,0.246662,-0.534830,-0.214098,0.1024,0.014512
2,8-MG-BA,0.788220,0.840168,0.628150,-1.331285,-0.248648,-0.386293,-0.297668,0.815664,-0.212430,...,-0.078537,-0.376219,-0.914794,0.283323,-0.551244,-0.333331,0.038996,-0.114577,0.1024,0.005537
3,GB-1,0.053174,-0.648190,-0.181854,-0.633104,-0.947646,-0.469195,-0.684658,0.421926,-0.905626,...,-0.194579,-0.275438,-0.562004,0.634896,-0.366795,0.442662,-1.225924,0.757517,0.1024,0.040831
4,NCI-H1648,1.519261,-0.368292,0.226856,-0.179698,-0.865956,-0.440831,1.035865,0.896539,1.694665,...,-0.480206,-0.311198,-0.414697,-0.112886,-0.841901,0.379371,1.731215,-1.545600,0.1024,0.005043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,CL-11,0.509973,0.547057,-0.601671,-0.464114,0.005193,-0.483587,-0.443398,0.765826,-0.753786,...,0.454603,0.216259,-1.002894,-1.029649,0.684973,-0.045526,-0.431420,-0.068895,0.1024,1.327531
395,COR-L95,-0.206808,-1.340759,-0.545395,-0.429504,-0.561951,-0.619859,-0.649944,0.262877,2.319067,...,-0.416340,-0.736149,-1.753831,-0.127193,-0.499025,0.121546,0.148885,-0.132204,0.1024,0.188277
396,NCI-H2135,1.066798,0.060061,-0.570217,-0.570037,-0.342490,-0.252140,-0.148907,1.091669,2.366973,...,-0.095038,-0.397918,0.051392,-0.628697,0.355916,0.640426,-0.067006,1.074772,0.1024,0.109464
397,ME-1,-1.079919,-0.198108,0.063834,0.553150,-0.359821,-0.325923,-0.550151,0.341530,0.670671,...,0.303012,-0.517000,-0.301867,1.009828,-0.353051,-1.128451,0.978038,1.259332,0.1024,0.580227
398,ROS-50,-1.067755,-0.034873,0.821478,-0.580824,0.084179,0.963640,-0.576919,-1.231046,-0.143699,...,-0.283344,-0.069726,1.472417,-0.258656,-0.001025,-0.644533,0.642495,1.238364,0.1024,0.358898

In [35]:
Columns_Intersection = test.columns.intersection(CCLE_PDX_Paclitaxel.columns)
test[Columns_Intersection]

,CELL_LINE_NAME,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,SLC35G6,OR4N3P,MRPL46,HPR,MIA,LINC00514,OR1D5,MYH4,KRT18P55,TBC1D3P5
0,MC-CAR,-1.184016,0.468235,0.485299,0.951035,0.705346,3.574280,-0.334766,-0.167187,-0.829344,...,-1.846231,-0.566142,0.639887,0.113480,0.157138,-0.504232,0.283905,0.443411,-0.006255,1.037289
1,SK-ES-1,0.949128,-0.099122,-1.142175,0.221316,0.582377,-0.500133,0.163121,-1.660569,-0.434605,...,0.513255,-0.173850,-0.518210,-1.023453,-0.407149,-0.924217,-0.198564,-0.151292,-0.534830,-0.214098
2,8-MG-BA,0.788220,0.840168,0.628150,-1.331285,-0.248648,-0.386293,-0.297668,0.815664,-0.212430,...,0.645411,-0.673028,-1.083025,0.357081,-0.078537,-0.376219,-0.914794,-0.551244,0.038996,-0.114577
3,GB-1,0.053174,-0.648190,-0.181854,-0.633104,-0.947646,-0.469195,-0.684658,0.421926,-0.905626,...,0.077844,-0.719733,-0.830098,-1.200791,-0.194579,-0.275438,-0.562004,-0.366795,-1.225924,0.757517
4,NCI-H1648,1.519261,-0.368292,0.226856,-0.179698,-0.865956,-0.440831,1.035865,0.896539,1.694665,...,-1.403287,-1.255556,0.313644,-0.783564,-0.480206,-0.311198,-0.414697,-0.841901,1.731215,-1.545600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,CL-11,0.509973,0.547057,-0.601671,-0.464114,0.005193,-0.483587,-0.443398,0.765826,-0.753786,...,1.019392,0.174648,1.578933,0.599214,0.454603,0.216259,-1.002894,0.684973,-0.431420,-0.068895
395,COR-L95,-0.206808,-1.340759,-0.545395,-0.429504,-0.561951,-0.619859,-0.649944,0.262877,2.319067,...,-1.074033,-0.756024,-2.464711,-0.524581,-0.416340,-0.736149,-1.753831,-0.499025,0.148885,-0.132204
396,NCI-H2135,1.066798,0.060061,-0.570217,-0.570037,-0.342490,-0.252140,-0.148907,1.091669,2.366973,...,3.252166,-0.225209,1.378062,-1.094202,-0.095038,-0.397918,0.051392,0.355916,-0.067006,1.074772
397,ME-1,-1.079919,-0.198108,0.063834,0.553150,-0.359821,-0.325923,-0.550151,0.341530,0.670671,...,-2.644663,-1.718953,-0.532261,0.974459,0.303012,-0.517000,-0.301867,-0.353051,0.978038,1.259332
398,ROS-50,-1.067755,-0.034873,0.821478,-0.580824,0.084179,0.963640,-0.576919,-1.231046,-0.143699,...,0.565056,-0.892936,-0.014946,0.146259,-0.283344,-0.069726,1.472417,-0.001025,0.642495,1.238364

In [36]:
CCLE_PDX_Paclitaxel[Columns_Intersection]

,CELL_LINE_NAME,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,SLC35G6,OR4N3P,MRPL46,HPR,MIA,LINC00514,OR1D5,MYH4,KRT18P55,TBC1D3P5
0,22RV1_PROSTATE,1.204591,-0.910305,1.755537,1.417053,1.409410,-0.104036,0.407742,1.700561,1.792728,...,0.635047,0.419469,1.578108,0.088949,-0.910305,0.435686,-0.910305,-0.910305,0.237652,-0.910305
1,42MGBA_CENTRAL_NERVOUS_SYSTEM,1.413846,-1.026812,1.736997,1.070785,1.109813,-0.057624,0.524472,1.598875,1.125621,...,0.310563,0.184717,1.490731,-1.026812,0.277465,-1.026812,-1.026812,-1.026812,-1.026812,-1.026812
2,5637_URINARY_TRACT,1.628673,-0.991209,1.749633,1.133871,1.355926,0.387527,0.898571,1.683850,1.218127,...,-0.991209,-0.991209,1.487167,-0.010632,0.959703,-0.991209,-0.991209,-0.991209,-0.991209,-0.991209
3,639V_URINARY_TRACT,1.401939,-1.087801,1.704798,0.987165,1.060926,-0.282543,1.209793,1.606918,1.272581,...,0.268067,-1.087801,1.403415,-0.232166,-1.087801,0.433227,-1.087801,-0.537630,-1.087801,-1.087801
4,697_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,0.367170,-1.028292,1.603076,1.218133,1.308746,0.119156,0.364395,0.512521,1.321451,...,0.150722,-1.028292,1.482315,-1.028292,-1.028292,-1.028292,-1.028292,-1.028292,-1.028292,-1.028292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,SKCO1_LARGE_INTESTINE,1.741510,-0.889931,1.803727,1.385127,1.327793,-0.889931,0.251299,1.785254,1.681568,...,0.419182,-0.889931,1.638471,-0.889931,0.999126,0.569653,-0.889931,0.657971,-0.889931,-0.889931
465,SNU449_LIVER,1.765621,-0.862985,1.885293,1.263060,1.372165,0.116889,1.377654,1.777108,1.443252,...,0.500176,-0.862985,1.574415,0.205121,0.688002,0.877394,-0.862985,-0.862985,-0.862985,-0.862985
466,T47D_BREAST,1.663326,-0.702386,2.075054,1.568291,1.543172,0.309977,0.514547,1.729573,1.620178,...,0.792146,-0.702386,1.851858,0.397639,-0.702386,1.018176,-0.702386,-0.702386,-0.702386,-0.702386
467,UACC257_SKIN,1.443127,-1.018997,1.662297,1.097454,1.240719,-0.030857,0.331932,1.597862,1.322649,...,0.519989,-1.018997,1.635501,-1.018997,1.689145,0.152124,-1.018997,-1.018997,-1.018997,-1.018997
468,VMRCRCW_KIDNEY,1.323815,-0.827025,1.826618,1.252796,1.038765,0.391160,1.470056,1.595563,1.653639,...,0.685821,-0.827025,1.612987,-0.827025,0.931505,0.762142,-0.827025,-0.827025,-0.827025,-0.827025

In [14]:
d = {'Name':['A', 'B'], 'col_1':[0, 0], 'col_2':[1, 2]}
df_1 = pd.DataFrame(data=d)
df_1

  Name  col_1  col_2
0    A      0      1
1    B      0      2

In [15]:
b = {'Name':['A', 'B', 'C'], 'col_2':[3, 4, 5]}
df_2 = pd.DataFrame(data=b)
df_2

  Name  col_2
0    A      3
1    B      4
2    C      5

In [16]:
df_3 = pd.merge(df_1, df_2, how='inner', on=['Name'])
df_3

  Name  col_1  col_2_x  col_2_y
0    A      0        1        3
1    B      0        2        4

In [19]:
import pandas as pd

# Creating Data frames
df1 = {'A': [1, 2, 3, 4],
		'B': ['abc', 'def', 'efg', 'ghi']}
df2 = {'A': [1, 2, 3, 4 ],
		'B': ['Geeks', 'For', 'efg', 'ghi'],
		'C':['Nikhil', 'Rishabh', 'Rahul', 'Shubham']}

d1 = pd.DataFrame(df1)
d2 = pd.DataFrame(df2)

In [20]:
d1

   A    B
0  1  abc
1  2  def
2  3  efg
3  4  ghi

In [21]:
d2

   A      B        C
0  1  Geeks   Nikhil
1  2    For  Rishabh
2  3    efg    Rahul
3  4    ghi  Shubham

In [22]:
# Calling merge() function
int_df = pd.merge(d1, d2, how ='inner', on =['A', 'B'])
print(int_df)

   A    B        C
0  3  efg    Rahul
1  4  ghi  Shubham

In [27]:
# creating dataframe1
dataFrame1 = pd.DataFrame({"Car": ['Bentley', 'Lexus', 'Tesla', 'Mustang', 'Mercedes', 'Jaguar'],
                           "Cubic_Capacity": [2000, 1800, 1500, 2500, 2200, 3000],
                           "Reg_Price": [7000, 1500, 5000, 8000, 9000, 6000]})

# creating dataframe2
dataFrame2 = pd.DataFrame({"Car": ['BMW', 'Lexus', 'Tesla', 'Mustang', 'Mercedes', 'Jaguar'],
                           "Units_Sold": [ 100, 110, 150, 80, 200, 90],
                           "Cubic_Capacity": [2000, 1800, 1500, 2500, 2200, 3000]})
dataFrame1

        Car  Cubic_Capacity  Reg_Price
0   Bentley            2000       7000
1     Lexus            1800       1500
2     Tesla            1500       5000
3   Mustang            2500       8000
4  Mercedes            2200       9000
5    Jaguar            3000       6000

In [28]:
dataFrame2

        Car  Units_Sold  Cubic_Capacity
0       BMW         100            2000
1     Lexus         110            1800
2     Tesla         150            1500
3   Mustang          80            2500
4  Mercedes         200            2200
5    Jaguar          90            3000

In [30]:
dataFrame3 = dataFrame2.columns.intersection(dataFrame1.columns)
dataFrame2[dataFrame3]

        Car  Cubic_Capacity
0       BMW            2000
1     Lexus            1800
2     Tesla            1500
3   Mustang            2500
4  Mercedes            2200
5    Jaguar            3000